# Generated by Django 5.2.17 on 2026-08-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
